// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.20.1
// source: pkg/api/master.proto

package master_slave

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// DiscoveryClient is the client API for Discovery service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DiscoveryClient interface {
	RegisterSlave(ctx context.Context, in *RegisterSlaveRequest, opts ...grpc.CallOption) (*RegisterSlaveResponse, error)
	GetSlavePprof(ctx context.Context, in *SlavePprofRequest, opts ...grpc.CallOption) (*SlavePprofResponse, error)
}

type discoveryClient struct {
	cc grpc.ClientConnInterface
}

func NewDiscoveryClient(cc grpc.ClientConnInterface) DiscoveryClient {
	return &discoveryClient{cc}
}

func (c *discoveryClient) RegisterSlave(ctx context.Context, in *RegisterSlaveRequest, opts ...grpc.CallOption) (*RegisterSlaveResponse, error) {
	out := new(RegisterSlaveResponse)
	err := c.cc.Invoke(ctx, "/api.Discovery/RegisterSlave", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *discoveryClient) GetSlavePprof(ctx context.Context, in *SlavePprofRequest, opts ...grpc.CallOption) (*SlavePprofResponse, error) {
	out := new(SlavePprofResponse)
	err := c.cc.Invoke(ctx, "/api.Discovery/GetSlavePprof", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DiscoveryServer is the server API for Discovery service.
// All implementations must embed UnimplementedDiscoveryServer
// for forward compatibility
type DiscoveryServer interface {
	RegisterSlave(context.Context, *RegisterSlaveRequest) (*RegisterSlaveResponse, error)
	GetSlavePprof(context.Context, *SlavePprofRequest) (*SlavePprofResponse, error)
	mustEmbedUnimplementedDiscoveryServer()
}

// UnimplementedDiscoveryServer must be embedded to have forward compatible implementations.
type UnimplementedDiscoveryServer struct {
}

func (UnimplementedDiscoveryServer) RegisterSlave(context.Context, *RegisterSlaveRequest) (*RegisterSlaveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RegisterSlave not implemented")
}
func (UnimplementedDiscoveryServer) GetSlavePprof(context.Context, *SlavePprofRequest) (*SlavePprofResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSlavePprof not implemented")
}
func (UnimplementedDiscoveryServer) mustEmbedUnimplementedDiscoveryServer() {}

// UnsafeDiscoveryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DiscoveryServer will
// result in compilation errors.
type UnsafeDiscoveryServer interface {
	mustEmbedUnimplementedDiscoveryServer()
}

func RegisterDiscoveryServer(s grpc.ServiceRegistrar, srv DiscoveryServer) {
	s.RegisterService(&Discovery_ServiceDesc, srv)
}

func _Discovery_RegisterSlave_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterSlaveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiscoveryServer).RegisterSlave(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Discovery/RegisterSlave",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiscoveryServer).RegisterSlave(ctx, req.(*RegisterSlaveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Discovery_GetSlavePprof_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SlavePprofRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DiscoveryServer).GetSlavePprof(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Discovery/GetSlavePprof",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DiscoveryServer).GetSlavePprof(ctx, req.(*SlavePprofRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Discovery_ServiceDesc is the grpc.ServiceDesc for Discovery service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Discovery_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.Discovery",
	HandlerType: (*DiscoveryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterSlave",
			Handler:    _Discovery_RegisterSlave_Handler,
		},
		{
			MethodName: "GetSlavePprof",
			Handler:    _Discovery_GetSlavePprof_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/api/master.proto",
}
