// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.0
// 	protoc        v3.20.1
// source: pkg/api/master.proto

package master_slave

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SlavePprofRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Slave_UUID string `protobuf:"bytes,1,opt,name=slave_UUID,json=slaveUUID,proto3" json:"slave_UUID,omitempty"`
	SlaveName  string `protobuf:"bytes,2,opt,name=slave_name,json=slaveName,proto3" json:"slave_name,omitempty"`
}

func (x *SlavePprofRequest) Reset() {
	*x = SlavePprofRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_master_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SlavePprofRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SlavePprofRequest) ProtoMessage() {}

func (x *SlavePprofRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_master_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SlavePprofRequest.ProtoReflect.Descriptor instead.
func (*SlavePprofRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_master_proto_rawDescGZIP(), []int{0}
}

func (x *SlavePprofRequest) GetSlave_UUID() string {
	if x != nil {
		return x.Slave_UUID
	}
	return ""
}

func (x *SlavePprofRequest) GetSlaveName() string {
	if x != nil {
		return x.SlaveName
	}
	return ""
}

type SlavePprofResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PprofResponse []byte `protobuf:"bytes,1,opt,name=pprof_response,json=pprofResponse,proto3" json:"pprof_response,omitempty"`
}

func (x *SlavePprofResponse) Reset() {
	*x = SlavePprofResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_master_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SlavePprofResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SlavePprofResponse) ProtoMessage() {}

func (x *SlavePprofResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_master_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SlavePprofResponse.ProtoReflect.Descriptor instead.
func (*SlavePprofResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_master_proto_rawDescGZIP(), []int{1}
}

func (x *SlavePprofResponse) GetPprofResponse() []byte {
	if x != nil {
		return x.PprofResponse
	}
	return nil
}

type RegisterSlaveRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message    string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	SlavePort  uint32 `protobuf:"varint,2,opt,name=slave_port,json=slavePort,proto3" json:"slave_port,omitempty"`
	Slave_UUID string `protobuf:"bytes,3,opt,name=slave_UUID,json=slaveUUID,proto3" json:"slave_UUID,omitempty"`
	SlaveName  string `protobuf:"bytes,4,opt,name=slave_name,json=slaveName,proto3" json:"slave_name,omitempty"`
}

func (x *RegisterSlaveRequest) Reset() {
	*x = RegisterSlaveRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_master_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterSlaveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterSlaveRequest) ProtoMessage() {}

func (x *RegisterSlaveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_master_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterSlaveRequest.ProtoReflect.Descriptor instead.
func (*RegisterSlaveRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_master_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterSlaveRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *RegisterSlaveRequest) GetSlavePort() uint32 {
	if x != nil {
		return x.SlavePort
	}
	return 0
}

func (x *RegisterSlaveRequest) GetSlave_UUID() string {
	if x != nil {
		return x.Slave_UUID
	}
	return ""
}

func (x *RegisterSlaveRequest) GetSlaveName() string {
	if x != nil {
		return x.SlaveName
	}
	return ""
}

type RegisterSlaveResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *RegisterSlaveResponse) Reset() {
	*x = RegisterSlaveResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_api_master_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RegisterSlaveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterSlaveResponse) ProtoMessage() {}

func (x *RegisterSlaveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_master_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterSlaveResponse.ProtoReflect.Descriptor instead.
func (*RegisterSlaveResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_master_proto_rawDescGZIP(), []int{3}
}

func (x *RegisterSlaveResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_pkg_api_master_proto protoreflect.FileDescriptor

var file_pkg_api_master_proto_rawDesc = []byte{
	0x0a, 0x14, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x03, 0x61, 0x70, 0x69, 0x22, 0x51, 0x0a, 0x11, 0x53,
	0x6c, 0x61, 0x76, 0x65, 0x50, 0x70, 0x72, 0x6f, 0x66, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x6c, 0x61, 0x76, 0x65, 0x5f, 0x55, 0x55, 0x49, 0x44, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x6c, 0x61, 0x76, 0x65, 0x55, 0x55, 0x49, 0x44, 0x12,
	0x1d, 0x0a, 0x0a, 0x73, 0x6c, 0x61, 0x76, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x73, 0x6c, 0x61, 0x76, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x3b,
	0x0a, 0x12, 0x53, 0x6c, 0x61, 0x76, 0x65, 0x50, 0x70, 0x72, 0x6f, 0x66, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x25, 0x0a, 0x0e, 0x70, 0x70, 0x72, 0x6f, 0x66, 0x5f, 0x72, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0d, 0x70, 0x70,
	0x72, 0x6f, 0x66, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x8d, 0x01, 0x0a, 0x14,
	0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x53, 0x6c, 0x61, 0x76, 0x65, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x1d,
	0x0a, 0x0a, 0x73, 0x6c, 0x61, 0x76, 0x65, 0x5f, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x09, 0x73, 0x6c, 0x61, 0x76, 0x65, 0x50, 0x6f, 0x72, 0x74, 0x12, 0x1d, 0x0a,
	0x0a, 0x73, 0x6c, 0x61, 0x76, 0x65, 0x5f, 0x55, 0x55, 0x49, 0x44, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x09, 0x73, 0x6c, 0x61, 0x76, 0x65, 0x55, 0x55, 0x49, 0x44, 0x12, 0x1d, 0x0a, 0x0a,
	0x73, 0x6c, 0x61, 0x76, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x73, 0x6c, 0x61, 0x76, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x22, 0x31, 0x0a, 0x15, 0x52,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x53, 0x6c, 0x61, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0x99,
	0x01, 0x0a, 0x09, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x76, 0x65, 0x72, 0x79, 0x12, 0x48, 0x0a, 0x0d,
	0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x53, 0x6c, 0x61, 0x76, 0x65, 0x12, 0x19, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x52, 0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x53, 0x6c, 0x61, 0x76,
	0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x52,
	0x65, 0x67, 0x69, 0x73, 0x74, 0x65, 0x72, 0x53, 0x6c, 0x61, 0x76, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x42, 0x0a, 0x0d, 0x47, 0x65, 0x74, 0x53, 0x6c, 0x61,
	0x76, 0x65, 0x50, 0x70, 0x72, 0x6f, 0x66, 0x12, 0x16, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x53, 0x6c,
	0x61, 0x76, 0x65, 0x50, 0x70, 0x72, 0x6f, 0x66, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x17, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x53, 0x6c, 0x61, 0x76, 0x65, 0x50, 0x70, 0x72, 0x6f, 0x66,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x29, 0x5a, 0x27, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x67, 0x6f, 0x6c, 0x61, 0x6e, 0x67, 0x2d,
	0x70, 0x72, 0x6f, 0x6a, 0x65, 0x63, 0x74, 0x73, 0x2f, 0x6d, 0x61, 0x73, 0x74, 0x65, 0x72, 0x5f,
	0x73, 0x6c, 0x61, 0x76, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_api_master_proto_rawDescOnce sync.Once
	file_pkg_api_master_proto_rawDescData = file_pkg_api_master_proto_rawDesc
)

func file_pkg_api_master_proto_rawDescGZIP() []byte {
	file_pkg_api_master_proto_rawDescOnce.Do(func() {
		file_pkg_api_master_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_api_master_proto_rawDescData)
	})
	return file_pkg_api_master_proto_rawDescData
}

var file_pkg_api_master_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pkg_api_master_proto_goTypes = []interface{}{
	(*SlavePprofRequest)(nil),     // 0: api.SlavePprofRequest
	(*SlavePprofResponse)(nil),    // 1: api.SlavePprofResponse
	(*RegisterSlaveRequest)(nil),  // 2: api.RegisterSlaveRequest
	(*RegisterSlaveResponse)(nil), // 3: api.RegisterSlaveResponse
}
var file_pkg_api_master_proto_depIdxs = []int32{
	2, // 0: api.Discovery.RegisterSlave:input_type -> api.RegisterSlaveRequest
	0, // 1: api.Discovery.GetSlavePprof:input_type -> api.SlavePprofRequest
	3, // 2: api.Discovery.RegisterSlave:output_type -> api.RegisterSlaveResponse
	1, // 3: api.Discovery.GetSlavePprof:output_type -> api.SlavePprofResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_api_master_proto_init() }
func file_pkg_api_master_proto_init() {
	if File_pkg_api_master_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_api_master_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SlavePprofRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_master_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SlavePprofResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_master_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterSlaveRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_api_master_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RegisterSlaveResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_api_master_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_api_master_proto_goTypes,
		DependencyIndexes: file_pkg_api_master_proto_depIdxs,
		MessageInfos:      file_pkg_api_master_proto_msgTypes,
	}.Build()
	File_pkg_api_master_proto = out.File
	file_pkg_api_master_proto_rawDesc = nil
	file_pkg_api_master_proto_goTypes = nil
	file_pkg_api_master_proto_depIdxs = nil
}
