// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.20.1
// source: pkg/api/server.proto

package master_slave

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// MasterClient is the client API for Master service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MasterClient interface {
	ReceiveHelloPingFromClient(ctx context.Context, in *HelloPingRequest, opts ...grpc.CallOption) (*HelloPingResponse, error)
	GetSlavePprof(ctx context.Context, in *SlavePprofRequest, opts ...grpc.CallOption) (*SlavePprofResponse, error)
}

type masterClient struct {
	cc grpc.ClientConnInterface
}

func NewMasterClient(cc grpc.ClientConnInterface) MasterClient {
	return &masterClient{cc}
}

func (c *masterClient) ReceiveHelloPingFromClient(ctx context.Context, in *HelloPingRequest, opts ...grpc.CallOption) (*HelloPingResponse, error) {
	out := new(HelloPingResponse)
	err := c.cc.Invoke(ctx, "/api.Master/ReceiveHelloPingFromClient", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *masterClient) GetSlavePprof(ctx context.Context, in *SlavePprofRequest, opts ...grpc.CallOption) (*SlavePprofResponse, error) {
	out := new(SlavePprofResponse)
	err := c.cc.Invoke(ctx, "/api.Master/GetSlavePprof", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MasterServer is the server API for Master service.
// All implementations must embed UnimplementedMasterServer
// for forward compatibility
type MasterServer interface {
	ReceiveHelloPingFromClient(context.Context, *HelloPingRequest) (*HelloPingResponse, error)
	GetSlavePprof(context.Context, *SlavePprofRequest) (*SlavePprofResponse, error)
	mustEmbedUnimplementedMasterServer()
}

// UnimplementedMasterServer must be embedded to have forward compatible implementations.
type UnimplementedMasterServer struct {
}

func (UnimplementedMasterServer) ReceiveHelloPingFromClient(context.Context, *HelloPingRequest) (*HelloPingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReceiveHelloPingFromClient not implemented")
}
func (UnimplementedMasterServer) GetSlavePprof(context.Context, *SlavePprofRequest) (*SlavePprofResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSlavePprof not implemented")
}
func (UnimplementedMasterServer) mustEmbedUnimplementedMasterServer() {}

// UnsafeMasterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MasterServer will
// result in compilation errors.
type UnsafeMasterServer interface {
	mustEmbedUnimplementedMasterServer()
}

func RegisterMasterServer(s grpc.ServiceRegistrar, srv MasterServer) {
	s.RegisterService(&Master_ServiceDesc, srv)
}

func _Master_ReceiveHelloPingFromClient_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloPingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterServer).ReceiveHelloPingFromClient(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Master/ReceiveHelloPingFromClient",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterServer).ReceiveHelloPingFromClient(ctx, req.(*HelloPingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Master_GetSlavePprof_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SlavePprofRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MasterServer).GetSlavePprof(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.Master/GetSlavePprof",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MasterServer).GetSlavePprof(ctx, req.(*SlavePprofRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Master_ServiceDesc is the grpc.ServiceDesc for Master service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Master_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.Master",
	HandlerType: (*MasterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReceiveHelloPingFromClient",
			Handler:    _Master_ReceiveHelloPingFromClient_Handler,
		},
		{
			MethodName: "GetSlavePprof",
			Handler:    _Master_GetSlavePprof_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/api/server.proto",
}
